# Generated by Django 5.1.5 on 2025-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
